export const SET_ERROR = "SET_ERROR";

export const SET_CURRENT_ENTITY = "SET_CURRENT_ENTITY";
export const SET_MENU_TREE_VISIBLE = "SET_MENU_TREE_VISIBLE";

export const SET_RESOURCES = "SET_RESOURCES";

export const SET_CURRENT_USER = "SET CURRENT USER";
